name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  heic2jpg_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Python packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        pip install -r heic2jpg/requirements.txt
      if: matrix.os == 'windows-latest'
      run: |
        pip install -r heic2jpg/requirements.txt
      
    - name: Build with Make
      run: |
        cd heic2jpg
        make
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: heic2jpg
        path: heic2jpg/dist/heic2jpg${{ matrix.os == 'windows-latest' && '.exe' || '' }}
